trigger: none

name: Write-File


variables:
- name: Environment
  value: IST
- group: secrets
- name: my-passed-var
  value: $[variables.serviceConnectionPrivateKeyPwd]

pool:
  vmImage: 'windows-2019'


jobs:
- job: readSecret
  steps:
  - task: PowerShell@2
    name: setTargets
    inputs:
      targetType: 'inline'
      script: |
        #starts here 
        Write-Host "##vso[task.setvariable variable=varFromJob1;isOutput=true;issecret=true]$(serviceConnectionPrivateKeyPwd)"
        Write-Host "The direct secret value is (task 1 serviceConnectionPrivateKeyPwd): $(serviceConnectionPrivateKeyPwd)"
        Write-Host "The runtime secret value is (task 1 varFromJob1): $[variables.varFromJob1]"
        Write-Host "The passed secret value is (task 1 my-passed-var): $(my-passed-var)"
  - script: echo Task 2- $(setTargets.varFromJob1)
    name: echoOutput