trigger: none

parameters:
  - name: AppName
    default: 'default'
  - name: AppID
    default: 'default'
  - name: Environment
    default: 'IST'
    type: string
    values:
    - DEV
    - IST
    - PRD

variables:
  - name: filesNotFound
    value: false
  - name: filePath
    value: "./EntraID/Applications-ADO/${{parameters.Environment}}/Apps-States/"
    
jobs:
- job:
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: PowerShell@2
      name: constructVariable
      inputs:
        targetType:  inline
        script: |

          if ( "${{parameters.AppID}}" -ne "default" ){
            write-host "Searching for App-State files using Application ID: ${{parameters.AppID}}"
            
          }elseif ( "${{parameters.AppID}}" -eq "default" ){

          }else{

          }  


    - task: PowerShell@2
      name: delete_App_Object
      inputs:
        targetType: 'filePath'
        filePath: './EntraID/Applications-ADO/Remove-Application-REST.ps1'
        arguments: '-appJsonFile "$(newAppJsonFilePath)" -tenantID $(tenantID) -ClientID $(ClientID) -certFile $(connectionCert.secureFilePath) -CertPwd $(serviceConnectionPrivateKeyPwd) -Environment ${{parameters.Environment}}'

    - task: PowerShell@2
      name: gitCommit
      inputs:  
        targetType: inline
        script: |
          git config --global user.email "entraidProject@azuredevops.com"
          git config --global user.name "serivce account"
          #cd $(Build.SourcesDirectory)\$(System.TeamProject)
          git add -A
          git commit -m "Delete App"
          git push origin HEAD:$(Build.SourceBranchName)