trigger: none

parameters:
  - name: firstName
    default: ''
  - name: lastName
    default: ''

jobs:
- job: PreProcessing
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: PowerShell@2
      name: setTargets
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "pre proccessing - ${{parameters.firstName}}"
          Write-Host "##vso[task.setvariable variable=firstNameVar;]${{parameters.firstName}}" 

- job: Processing
  dependsOn: PreProcessing
  displayName: Build source
  strategy:
    matrix: $[ dependencies.PreProcessing.outputs['setTargets.firstNameVar'] ]
  variables:
    targets: $[ dependencies.PreProcessing.outputs['setTargets.firstNameVar'] ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Hello from second pipeline 2 task 1 $(Work)"
    - task: PowerShell@2
      #condition: and(succeeded(), ${{ eq(parameters.firstName, 'Tim') }})
      condition: eq(variables.Work, 'Tim')
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Hello from second pipeline 2 task 2 $(Work)"
