trigger: none

parameters:
  - name: AppName
    default: 'Test-OIDC-App-123'
  - name: csvFileName
    default: 'defaultCSV'
  - name: Environment
    default: 'IST'
    type: string
    values:
    - DEV
    - IST
    - PRD

variables:
  - name: step1succeed
    value: false
  - name: step2succeed
    value: false
  - name: step3succeed
    value: false
# - name: skipGit
  - name: filesNotFound
    value: false
  - group: ${{parameters.Environment}}-Variables
  - group: ${{parameters.Environment}}-Secrets
  - name: tenantIDvar
    value: $[variables.tenantID]

pool:
  vmImage: 'windows-latest'

jobs:
- job: 
  pool:
    vmImage: 'windows-latest'
    steps:
      - checkout: self
        persistCredentials: true
      - task: PowerShell@2
        name: constructVariables
        inputs:
          targetType: inline
          script: |
            $tenantID = "$(tenantIDvar)"
            Write-Host "tenantID: $(tenantID)"
            Write-Host "tenantID: $(serviceConnectionPrivateKeyPwd)"
            $(serviceConnectionPrivateKeyPwd) | Out-file -force whatif.txt
            
      - task: PowerShell@2
        name: gitCommit
        inputs:  
          targetType: inline
          script: |
            git config --global user.email "entraidProject@azuredevops.com"
            git config --global user.name "serivce account"
            git fetch origin $(Build.SourceBranchName):tmp
            git rebase tmp
            git add -A
            git commit -m "new txt file"
            git push origin HEAD:$(Build.SourceBranchName)