trigger: none

parameters:
  - name: AppName
    default: 'Test-OIDC-App-123'
  - name: csvFileName
    default: 'defaultCSV'
  - name: Environment
    default: 'IST'
    type: string
    values:
    - DEV
    - IST
    - PRD

variables:
  - name: step1succeed
    value: false
  - name: step2succeed
    value: false
  - name: step3succeed
    value: false
# - name: skipGit
  - name: filesNotFound
    value: false
  - group: ${{parameters.Environment}}-Variables
  - group: ${{parameters.Environment}}-Secrets
  - name: tenantIDvar
    value: $[variables.tenantID]

pool:
  vmImage: 'windows-latest'

jobs:
- job: 
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: PowerShell@2
      name: setTargets
      inputs:
        targetType: 'filePath'
        filePath: './EntraID/Applications-ADO/PowerShell_Script.ps1'
        arguments: '-ApplicationID $(ApplicationID) -tenantID $(tenantID) -ClientID $(ClientID) -certFile $(certFile) -CertPwd $(CertPwd) -Environment $(Environment)'
