trigger: none

parameters:
  - name: Environment
    default: 'IST'
    type: string
    values:
    - DEV
    - IST
    - PRD


variables:
  - group: ${{parameters.Environment}}-Variables
  - group: ${{parameters.Environment}}-Secrets
  - name: tenantIDvar
    value: $[variables.tenantID]

pool:
  vmImage: 'windows-latest'

jobs:
- job: Start
  steps:
    - checkout: self
      persistCredentials: true
    - task: DownloadSecureFile@1
      name: abc
      displayName: 'Download abc certificate'
      inputs:
        secureFile: 'abc.com.pfx'
    - task: PowerShell@2
      name: constructVariables
      inputs:
        targetType: inline
        script: |
          $tenantID = "$(tenantIDvar)"
          Write-Host "tenantID: $tenantID"
          Write-Host "tenantID: $(serviceConnectionPrivateKeyPwd)"
          #"$(abc-private)" | Out-file -force whatif.txt
          # Get the keys from the certificate file (pfx file)
          $privateKeyPwd = "$(serviceConnectionPrivateKeyPwd)""
          $privatePwdSecure = ConvertTo-SecureString -String $privateKeyPwd -Force -AsPlainText
          $pfxCertFile = $(abc.secureFilePath)
          $pfxCert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($pfxCertFile,$privatePwdSecure)
          #$pfxCert | Export-Certificate -FilePath $tmpPubCertFile -Type CERT
          if ( $($PSVersionTable.PSVersion.Major) -eq 7 ){
              #$publicKey = [convert]::ToBase64String((Get-Content $tmpPubCertFile -AsByteStream -Raw))
              $privateKey2 = [convert]::ToBase64String((pfxCert)) 
              $privateKey = [convert]::ToBase64String((Get-Content $PfxCertFile -AsByteStream -Raw)) 
          }else{
              #$publicKey = [convert]::ToBase64String((Get-Content $tmpPubCertFile -Encoding Byte))
              $privateKey2 = [convert]::ToBase64String((pfxCert)) 
              $privateKey = [convert]::ToBase64String((Get-Content $PfxCertFile -Encoding Byte))  
          }
          "abc-in-library- $privateKey & abc-in-library2- $privateKey2 & abc-in-AKV- $(abc-private)" | Out-file -force whatif.txt
    - task: PowerShell@2
      name: gitCommit
      inputs:  
        targetType: inline
        script: |
          git config --global user.email "entraidProject@azuredevops.com"
          git config --global user.name "serivce account"
          git fetch origin $(Build.SourceBranchName):tmp
          git rebase tmp
          git add -A
          git commit -m "new txt file"
          git push origin HEAD:$(Build.SourceBranchName)