trigger: none
 
name: Write-File
 
parameters:
  - name: Environment
    displayName: Environment
    default: 'IST'
    type: string
    values:
    - IST
    - UAT
    - PRD
 
  - name: AppName
    displayName: (Mandatory) Application Name
    default: ''
 
  - name: AppType
    displayName: (Mandatory) Application Type
    default: 'SAML'
    type: string
    values:
    - SAML
    - OIDC
 
  - name: EntityID
    displayName: (Mandatory) Application entity ID or Identifier URI (EntityID/identifierUris)
    default: ''
    type: string
 
  - name: ACSredirecturi
    displayName: (Mandatory) ACS URLs or Redirect URIs (sperated by comma)
    type: string
    default: ''
 
  - name: assuranceLevel
    displayName: (Mandatory) Assurance Level of the application
    default: 'Medium'
    type: string
    values:
    - Low
    - Medium
    - High
    - Critical
 
  - name: requireBankIssuedDevices
    displayName: (Mandatory) Require Bank Issued Devices
    default: 'False'
    type: string
    values:
    - True
    - False
 
  - name: requireVerificationCert
    displayName: (Mandatory) Require verification certificates
    default: 'False'
    type: string
    values:
    - True
    - False
 
  - name: Description
    displayName: (Optional) Application Description
    default: 'Default'
    type: string
 
  - name: nameIdFormat
    displayName: (Mandatory) Claim Name (SAML2 only)- Unique User Identifier (Name ID)
    default: 'emailAddress'
    type: string
    values:
    - emailAddress
    - unspecified
 
  - name: nameidentifierAttribute
    displayName: (Mandatory) Claim Value -  User Attribute for the nameId
    default: 'mail'
    type: string
 
  - name: SSOID
    displayName: (Optional) Claim Name - ScotiaID (eg. bnsScotiaID or SSOID'. Leave it as Default if not needed)
    default: 'Default'
    type: string
 
  - name: SSOIDAttribute
    displayName: Claim Value
    default: 'extension_73f338a4697b4577bd8334ffb89ccdb4_employeeNumber'
    type: string

  - name: claim1
    displayName: (Optional) Claim Name - Claim 1
    default: 'Default'
    type: string
 
  - name: claim1Attribute
    displayName: Claim Value - Claim 1
    default: 'Default'
    type: string
 
  - name: TransitId
    displayName: (Optional) Claim Name - TransitId
    default: 'Default'
    type: string
 
  - name: TransitIdAttribute
    displayName: Claim Attribute - TransitId
    default: 'Default'
    type: string
  
  - name: groupclaimName
    displayName: (Optional) Group Claim Name - (Can be customized. Put null if no group claim is needed.)
    default: 'default'
    type: string
 
  - name: groupClaimRegex
    displayName: (Optional) Claim Value - Group regex match pattern (Leave it as default, if Regex isn't needed)
    default: 'default'
    type: string
 
  - name: groupclaimRegexReplace
    displayName: (Optional) Claim Value - Group regex replacement pattern (Leave it as default, if Regex isn't needed)
    default: 'default'
    type: string
 
variables:
  - name: stepSucceed
    value: false
  - name: AppStagingFolderPath
    value: "./${{parameters.Environment}}/Staging"
  - name: templateFolderPath
    value: "EntraID/Applications-ADO/IST/Staging/Templates"
  - name: SAMLappTemplateName
    value: "SAML_App_Template.json"
  - name: OIDCappTemplateName
    value: "OIDC/OIDC_App_Template.json"
  - name: SAMLClaimsTemplateName
    value: "SAML_Claims_Template.json"  
  - group: ${{parameters.Environment}}-Variables
  - name: tenantIDvar
    value: $[variables.tenantID]
 
pool:
  vmImage: 'windows-latest'
 
jobs:
- job: ${{ replace(parameters.AppName,'-','_') }}_Create_Template
  displayName: Generate staging templates
 
  steps:
  - checkout: self
    persistCredentials: true
  - task: PowerShell@2
    name: createTemplates
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem "$(AppStagingFolderPath)"
        Write-host "-______________-"
        Get-ChildItem "$(templateFolderPath)"
          ################################################
          # SAML Apps.                                   #
          ################################################
        if ( "${{parameters.AppType}}" -eq "SAML" ){
          $templateFileAppObj = Get-content -Path "$(templateFolderPath)/$(SAMLappTemplateName)" -RAW | ConvertFrom-Json
                  
          ###########################
          ### Begin: App Template ###
          
          #AppName
          $templateFileAppObj.displayName = "${{parameters.AppName}}"
 
          #EntityID
          $arrayEntity = @('${{parameters.EntityID}}')
          $templateFileAppObj.identifierUris = $arrayEntity
 
          #ACSredirectUris
          $arrayACSredirecturi = @()
          $acsUris = '${{parameters.ACSredirecturi}}'.Split(',')
          foreach ($uri in $acsUris) {
              $trimmedUri = $uri.Trim()
              if ($trimmedUri -ne '') {
                  $arrayACSredirecturi += $trimmedUri
              }
          }
          $templateFileAppObj.web.redirectUris = $arrayACSredirecturi
 
          #Description
          if ("${{parameters.Description}}" -ne "Default"){
            $templateFileAppObj.Description = "${{parameters.Description}}"
          }

          # Require verification cert
          if ("${{parameters.requireVerificationCert}}" -ne "False"){
            $templateFileAppObj.requestSignatureVerification.isSignedRequestRequired = "${{parameters.requireVerificationCert}}"
          }

          ### End: App Template ###
          #########################

          #######################
          ### Claims Template ###

          $templateFileClaimObj = Get-content -Path "$(templateFolderPath)/$(SAMLClaimsTemplateName)" -RAW | ConvertFrom-Json

          # Name ID format
          $NameIDClaim = $templateFileClaimObj.claims | Where-Object { $_."@odata.type" -eq '#microsoft.graph.samlNameIdClaim' }
          $NameIDClaim.nameIdFormat = "${{parameters.nameIdFormat}}"
          $NameIDClaim.configurations.attribute.id = "${{parameters.nameidentifierAttribute}}"

          # Get REF claims object
          $ReferenceClaim = $templateFileClaimObj.claims | Where-Object { $_.name -eq "referenceClaim" }

          # Scotia ID
          if ( "${{parameters.SSOID}}" -ne "Default"){
            $scotiaIDClaim = $ReferenceClaim | ConvertTo-Json -Depth 10 | ConvertFrom-Json
            $scotiaIDClaim.name = "${{parameters.SSOID}}"
            $scotiaIDClaim.configurations.attribute.id = "${{parameters.SSOIDAttribute}}"
            #Add Obj to Claims object
            $templateFileClaimObj.claims += $scotiaIDClaim
          }

          # Transit ID
          if ( "${{parameters.TransitId}}" -ne "default"){
            $TransitIDClaim = $ReferenceClaim | ConvertTo-Json -Depth 10 | ConvertFrom-Json
            $TransitIDClaim.name = "${{parameters.TransitId}}"
            $TransitIDClaim.configurations.attribute.id = "${{parameters.TransitIdAttribute}}"
            #Add Obj to Claims object
            $templateFileClaimObj.claims += $TransitIDClaim
          }

          ##### Duplicate this block for more optional claims #####
          # Claim 1
          if ( "${{parameters.claim1}}" -ne "default"){
            $claim1 = $ReferenceClaim | ConvertTo-Json -Depth 10 | ConvertFrom-Json
            $claim1.name = "${{parameters.claim1}}"
            $claim1.configurations.attribute.id = "${{parameters.claim1Attribute}}"
            #Add Obj to Claims object
            $templateFileClaimObj.claims += $TransitIDClaim
          }

          # Group Claim
          if ( "${{parameters.groupclaimName}}" -eq "null"){  # no group claims
            #Removing Group Claim block (only if group claim isn't need)
            $templateFileClaimObj.claims = $templateFileClaimObj.claims | Select-Object * | Where { $_.name -ne "defaultGroupClaimName" }

            # App manifest template modify
            $templateFileAppObj.groupMembershipClaims = $null
            $emptyObjArray = New-Object -TypeName System.Collections.ArrayList
            #Removing the saml2Token block
            $templateFileAppObj.optionalClaims.saml2Token =  $emptyObjArray
          
          }else{   #With Group claims

            # Option 1 - default group claim name + no RegEx
            if ( "${{parameters.groupclaimName}}" -eq "default" -and "${{parameters.groupClaimRegex}}" -eq "default"){
              #Removing Group Claim block (only if group claim isn't need)
              $templateFileClaimObj.claims = $templateFileClaimObj.claims | Select-Object * | Where { $_.name -ne "defaultGroupClaimName" }

             # Option 2 - default group claim name + With Regex match and replace
            }elseif( "${{parameters.groupclaimName}}" -eq "default" -and "${{parameters.groupClaimRegex}}" -ne "default") {
              $groupClaim = $templateFileClaimObj.claims | Where-Object { $_.'name' -eq "defaultGroupClaimName" }
              $groupClaim.name = "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
              $groupClaim.configurations.transformations.regex = "${{parameters.groupClaimRegex}}"
              $groupClaim.configurations.transformations.replacement = "${{parameters.groupclaimRegexReplace}}"
              
              # Option 3 - custom Group claim Name + no Regex
            }elseif( "${{parameters.groupclaimName}}" -ne "default" -and "${{parameters.groupClaimRegex}}" -eq "default") {
              $groupClaim = $templateFileClaimObj.claims | Where-Object { $_.'name' -eq "defaultGroupClaimName" }
              $groupClaim.name = "${{parameters.groupclaimName}}"
              $emptyObjArray = New-Object -TypeName System.Collections.ArrayList
              # Removing the Transformations blcok
              $groupClaim.configurations | % { $_.transformations = $emptyObjArray } 

              # Option 4 - custom Group claim Name + With Regex match and replace
            }else{
              $groupClaim = $templateFileClaimObj.claims | Where-Object { $_.'name' -eq "defaultGroupClaimName" }
              $groupClaim.name = "${{parameters.groupclaimName}}"
              $groupClaim.configurations.transformations.regex = "${{parameters.groupClaimRegex}}"
              $groupClaim.configurations.transformations.replacement = "${{parameters.groupclaimRegexReplace}}"

            }
            # App manifest template  modify ** nothing to change **
          }

          #Removing Reference Claims block
          $templateFileClaimObj.claims = $templateFileClaimObj.claims | Select-Object * | Where { $_.name -ne "referenceClaim" } 


          ################################################
          # OIDC Apps.                                   #
          ################################################
        }else{ #OIDC
          
        }
 
        ################################################
        # Files Output                                 #
        ################################################       
 
        #App Staging File
        $AppStagingOutput = $templateFileAppObj | ConvertTo-Json -Depth 20
        $AppStagingFilePath = "$(AppStagingFolderPath)/${{parameters.AppName}}_App.json"
        $AppStagingOutput | Out-File -FilePath $AppStagingFilePath -Force
 
        # SP Staging File
        $SPTemplatebody = @"
        {
            "preferredSingleSignOnMode" : "Value",
            "customSecurityAttributes":
            {
                "Application":
                {
                    "@odata.type":"#Microsoft.DirectoryServices.CustomSecurityAttributeValue",
                    "AssuranceLevel":"DefaultAttributeValue",
                    "RequireBankIssuedDevices":"DefaultAttributeValue"
                }
            }
        }
        "@
 
        $SPTemplateObj = $SPTemplatebody | ConvertFrom-Json
        if ( "${{parameters.AppType}}" -eq "SAML"){
          $SPTemplateObj.preferredSingleSignOnMode = "saml"
        }else{
          $SPTemplateObj.preferredSingleSignOnMode = "oidc"
        }
        $SPTemplateObj.customSecurityAttributes.Application.AssuranceLevel = "${{parameters.assuranceLevel}}"
        $SPTemplateObj.customSecurityAttributes.Application.RequireBankIssuedDevices = "${{parameters.requireBankIssuedDevices}}"
 
        $SpStagingOutput = $SPTemplateObj | ConvertTo-Json -Depth 20
        $SpStagingFilePath = "$(AppStagingFolderPath)/${{parameters.AppName}}_Sp.json"
        $SpStagingOutput | Out-File -FilePath $SpStagingFilePath -Force
 
        # Claim Staging File
        $claimStagingOutput = $templateFileClaimObj | ConvertTo-Json -Depth 30
        $claimStagingFilePath = "$(AppStagingFolderPath)/${{parameters.AppName}}_customClaims.json"
        $claimStagingOutput | Out-File -FilePath $claimStagingFilePath -Force
 
  - script: echo Task 2 filename - $(fileName)
    name: echoOutput
  - task: PowerShell@2
    name: gitCommit
    inputs:  
      targetType: inline
      script: |
        git config --list
        Write-host 'git add -A'
        git status
        git add -A
        git status
        git commit -m "Template file created"
        $retryLimit = 20
        $i = 0
        do {
            $i++
            Write-Host "Git commit attempt: $i"
            $waitTime = Get-Random -Minimum 5 -Maximum 15
            Start-Sleep -s $waitTime
            $LASTEXITCODE=0
            Write-host 'git pull --rebase origin $(Build.SourceBranchName)'
            git pull --rebase origin $(Build.SourceBranchName)
            Write-host "LASTEXITCODE = $LASTEXITCODE"
            Write-host 'git push origin HEAD:$(Build.SourceBranchName)'
            git push origin HEAD:$(Build.SourceBranchName)
            Write-host "LASTEXITCODE =  $LASTEXITCODE"
          }while($LASTEXITCODE -and $i -le $retryLimit)