trigger: none

# Need both Name and ID
parameters:
  - name: AppName
    default: 'defaultparaAppName'
  - name: AppID
    default: 'defaultparaAppID'
  - name: csvFileName
    default: 'defaultCSV'
  - name: Environment
    default: 'IST'
    type: string
    values:
    - DEV
    - IST
    - PRD

variables:
  - name: stepSucceed
    value: false
  - name: AppStatesFolderPath
    value: "./EntraID/Applications-ADO/${{parameters.Environment}}/Apps-States"
  - name: AppStagingFolderPath
    value: "./EntraID/Applications-ADO/${{parameters.Environment}}/Staging"   
  - group: ${{parameters.Environment}}-Variables
  - group: ${{parameters.Environment}}-Secrets
  - name: tenantIDvar
    value: $[variables.tenantID]
    
pool:
  vmImage: 'windows-latest'

jobs:
- deployment: ${{ replace(parameters.csvFileName,'.','_')}}__UPDATE_APP_OBJ__${{ replace(parameters.AppName,'-','_') }}_${{ replace(parameters.AppID,'-','_') }}
  environment: ${{parameters.Environment}}
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            persistCredentials: true
          - task: PowerShell@2
            name: constructVariables
            inputs:
              targetType: inline
              script: |
                $tenantID = "$(tenantIDvar)"
                #Write-Host "tenant ID is $tenantID"
                Write-Host "tenantID: $(tenantID)"
                 # -----Updating app by locating application with App ID---- 
                if ( "${{parameters.AppID}}" -ne "defaultparaAppID" -and "${{parameters.AppName}}" -ne "defaultparaAppName" ){
                  # Proceed
                  $appFileName = "${{parameters.AppName}}_${{parameters.AppID}}_Application.json"
                  $appStagingFileName = "${{parameters.AppName}}_App.json"
                  $appStagingJsonFile = "$(AppStagingFolderPath)"+"/"+"$appStagingFileName"
                  $appJsonFile = "$(AppStatesFolderPath)"+"/"+"$appFileName"
                  Write-Host "##vso[task.setvariable variable=appStagingJsonFile]$appStagingJsonFile"
                  Write-Host "appStagingJsonFile: $appStagingJsonFile"
                  Write-Host "##vso[task.setvariable variable=appJsonFile]$appJsonFile"
                  Write-Host "appJsonFile: $appJsonFile"
                }else{
                  #abort
                  Throw "Please provide both Application Name and ID"
                }

          - task: PowerShell@2
            name: verifyFiles
            inputs:
              targetType: inline
              script: |
                if (-not (Test-Path -Path '$(appStagingJsonFile)')){
                  $stagingFile = $false
                  throw "Staging File - $(appStagingJsonFile) not Found"
                }else{
                  Write-Host "App Staging File with App Name: ${{parameters.AppName}} found: $(appStagingJsonFile)"
                }
                if (-not (Test-Path -Path '$(appJsonFile)')){
                  $appStateFile = $false
                  throw "State File - $(appJsonFile) not Found"
                  # To do: make a boolean to run a step for using a powershell script to check if application exists on Entra ID matching both app and ID
                }else{
                  Write-Host "App State File with App Name: ${{parameters.AppName}} found: $(appJsonFile)"
                }
          - task: DownloadSecureFile@1
            name: connectionCert
            displayName: 'Download Service Connection certificate'
            inputs:
              secureFile: '${{parameters.Environment}}-Service-Connection.pfx'

          - task: PowerShell@2
            name: Update_Application_obj
            inputs:
              targetType: 'filePath'
              filePath: './EntraID/Applications-ADO/Update-Applicaton-REST.ps1'
              arguments: '-JsonFile "$(appJsonFile)" -newJsonFile "$(appStagingJsonFile)" -tenantID $(tenantID) -ClientID $(ClientID) -certFile $(connectionCert.secureFilePath) -CertPwd $(serviceConnectionPrivateKeyPwd) -Environment ${{parameters.Environment}}'

          - task: PowerShell@2
            name: stepCheck
            condition: succeeded()
            inputs:
              targetType: inline
              script: |
                Write-Host "##vso[task.setvariable variable=stepSucceed]true"


          - task: PowerShell@2
            name: Post_Deployment_CleanUP
            condition: always()
            inputs:
              targetType: inline
              script: |
                if (("$(stepSucceed)" -eq "false")){ 
                  write-host "Update Application Obj failed"
                }else{
                  write-host "Update Application Obj succeeded."
                }

          - task: PowerShell@2
            name: gitCommit
            #condition: eq(variables.skipGit, 'false')
            condition: eq(variables.stepSucceed, 'true')
            inputs:  
              targetType: inline
              script: |
                git config --global user.email "entraidProject@azuredevops.com"
                git config --global user.name "serivce account"
                git fetch origin $(Build.SourceBranchName):tmp
                git rebase tmp
                git add -A
                git commit -m "Updated app obj - ${{parameters.AppName}}"
                git push origin HEAD:$(Build.SourceBranchName)
          #- checkout: self
            #clean: true